// DllRegExt.idl: DllRegExt 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 生成类型库(DllRegExt.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,
	pointer_default(unique)
]
interface IComponentRegistrar : IDispatch
{
	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
	[id(2)]	HRESULT RegisterAll();
	[id(3)]	HRESULT UnregisterAll();
	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
};

[
	object,
	uuid(425695e9-8f6f-416c-afcb-c824d795c65b),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IDllRegEx : IDispatch
{
};
[
	object,
	uuid(14af87d8-3ff9-4261-aad8-c384b6740af9),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ISubIExCmdMenu : IDispatch
{
};
[
	uuid(3ba066fc-e493-451b-a26f-86b9841f1fe1),
	version(1.0),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a,"{c0444687-aa57-4638-8140-1602aa6eef73}")
]
library DllRegExtLib
{
	importlib("stdole2.tlb");
	[
		uuid(c0444687-aa57-4638-8140-1602aa6eef73)
	]
	coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};
	[
		uuid(9dd00a4a-9701-4c02-813c-2fd842b33587)
	]
	coclass DllRegEx
	{
		[default] interface IDllRegEx;
	};
	[
		uuid(8ccde13c-213f-4eac-ac9e-c35253dcee96)
	]
	coclass SubIExCmdMenu
	{
		[default] interface ISubIExCmdMenu;
	};
};

import "shobjidl.idl";
import "shobjidl.idl";
