// UserExt.idl: UserExt 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 生成类型库(UserExt.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,
	pointer_default(unique)
]
interface IComponentRegistrar : IDispatch
{
	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
	[id(2)]	HRESULT RegisterAll();
	[id(3)]	HRESULT UnregisterAll();
	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
};
[
	object,
	uuid(2d6465c6-f7db-4b6a-a456-b76be89b794e),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IExplorerCmd : IDispatch
{
};
[
	object,
	uuid(28c5fa1a-e446-4a52-ba2d-c15dcdd8dbd8),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ISubIExCmdRoot : IDispatch
{
};
[
	uuid(cba63cca-446c-4ded-a68c-3be1e7fdec41),
	version(1.0),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a,"{aea65d79-6733-450f-89fa-cabbc58c5bc4}")
]
library UserExtLib
{
	importlib("stdole2.tlb");
	[
		uuid(aea65d79-6733-450f-89fa-cabbc58c5bc4)
	]
		coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};
	[
		uuid(9f0bd2d5-02f6-4672-8d3a-4512cadecc6f)
	]
	coclass ExplorerCmd
	{
		[default] interface IExplorerCmd;
	};
	[
		uuid(89d42831-4128-4aba-a79b-eb734e8e8dc1)
	]
	coclass SubIExCmdRoot
	{
		[default] interface ISubIExCmdRoot;
	};
}

import "shobjidl.idl";
import "shobjidl.idl";
import "shobjidl.idl";
